### ISSUE TITLE
Autentificación HWID

### ISSUE THREAD

**Issue by YTONYOUTUBETUBEYOUONTU** [omarperez77/IS2024#10]
### Agregar un metodo de Autentificación para entrar al sistema.
---
**Elementos:**
- HWID

**opcional:** 

- Usuario
- Contraseña

**Comment by Folynsky** [comment]
Avance: vamos bien

**Comment by Folynsky** [comment]
Funcionalidad de login agregada
Falta realizar una mejorar de diseño en el apartado
Opcional: Enlazar el login a la base de datos para un manejo de los usaurios
