### ISSUE TITLE
Revisar el buen funcionamiento del backend

### ISSUE THREAD

**Issue by omarperez77** [omarperez77/IS2024#2]
- [x] Clonar el repositorio
- [x] Actualizar configuracion de conexion a BD
- [x] Ejecutar la API 
- [x] A traves de thunder client verificar el funcionamiento de las peticiones CRUD

**Comment by Folynsky** [comment]
Ya quedo

**Comment by YTONYOUTUBETUBEYOUONTU** [comment]
a

**Comment by YTONYOUTUBETUBEYOUONTU** [comment]
ya quedo

**Comment by omarperez77** [comment]
Verificar de nuevo. Se reviso en el deployment y no funciona.
