### ISSUE TITLE
Listado de empleados y listado de departamentos

### ISSUE THREAD

**Issue by Folynsky** [omarperez77/IS2024#6]
Agregar la funcionalidad que permita alternar entre el listado de los empleados y el listado de departamentos dentro del CRUD, el alternado de la vista debera accionarse al presionar un boton para el listado de empleados y un boton para el listado de departamentos respectivamente

**Comment by JCarlos117** [comment]
ponerse al dia con la actividad asignada

**Comment by YTONYOUTUBETUBEYOUONTU** [comment]
Favor de subir avances del trabajo

**Comment by YTONYOUTUBETUBEYOUONTU** [comment]
ya casi?

**Comment by ValeMP12** [comment]
Ya mero patrón, yo trabajo lo que me pagan
