### ISSUE TITLE
Pruebas y reporte de errores

### ISSUE THREAD

**Issue by Folynsky** [omarperez77/IS2024#8]
- [x] Realizar pruebas de funcionalidad dentro del CRUD
- [x] Generar un listado de errores/bugs del proyecto (de ser necesario)
- [x] Generar un listado de posibles mejoras posterior a las pruebas (de ser necesario)

**Comment by JaimeCanedo** [comment]
Listado de errores
-El INPUT del apartado nombre de ambos FORM pueden tomar valores numéricos, aceptan nombres vacíos, y también acepta caracteres especiales.
-El INPUT del apartado sueldo en el FORM empleados acepta valores negativos, también acepta la letra 'e'.
-El INPUT del apartado departamento tanto del apartado sueldo en FORM de modificar empleados acepta la letra 'e', puntos decimales, valores negativos
-El INPUT del apartado nombre en FORM de modificar empleados acepta valores numéricos, acepta nombres vacíos y caracteres especiales. 
-El INPUT del apartado nombre en FORM de modificar departamentos acepta valores numéricos, acepta nombres vacíos y caracteres especiales. 

Listado de soluciones
-Se podrían realizar un par de validaciones en cada tipo de dato para evitar la fuga de datos erróneos en los nuevos registros.
-Se podría realizar una mejor estructura en el formato de modificar, ya que el formato que maneja es poco visto y difícil de validar de la manera que se presenta.
